export const users = [
    {
        id: 1,
        name: "Tom Cruise",
        image: "https://pyxis.nymag.com/v1/imgs/4e5/1f7/a917c50e70a4c16bc35b9f0d8ce0352635-14-tom-cruise.rsquare.w700.jpg",
        status: "online",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "I have to give a presentation on global warming on Friday, and I am so nervous.",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "First of all, you need to understand the subject matter thoroughly. You need to know what is global warming, what causes global warming, and what people should do to abate the effects of global warming",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I have done a lot of research on the subject, and I know I can answer any questions I will receive from the audience.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I should talk about more precisely the sequence of my presentation?",
                self: false,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Yes, what you should present first, second and third",
                self: true,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If that is the case, then I already have an outline. To make it easy for my audience to follow the presentation, I intend to post the outline on the board at all time during my speech.",
                self: false,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "No, I have not thought about that. I better get some statistics from the Internet. I should not have any problems since the Internet has all kinds of data.",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Pictures will keep your audience from being bored. In order for you to succeed, you need to keep them interested and involved.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "You are absolutely right. I will take time to practice and to learn to relax and express myself really well. Wish me luck.",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I know you. You can do it. Good luck",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 2,
        name: "Leonardo DiCaprio",
        image: "https://pyxis.nymag.com/v1/imgs/4d0/153/d805ddfbb5331ba08109664e816b79b8d0-8-Leonardo-DiCaprio.rsquare.w330.jpg",
        status: "busy",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "Hey Anik? Is it you?",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Oh Leo! How are you? It’s been a long time.",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I am fine, what about you? Yes, we last met during the board exams.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I’m good too",
                self: true,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "What are you doing now?",
                self: false,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Well, I have started my undergraduate studies in English Honours at St. Xaviers College in Mumbai.",
                self: true,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "No, I have not thought about that. I better get some statistics from the Internet. I should not have any problems since the Internet has all kinds of data.",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Pictures will keep your audience from being bored. In order for you to succeed, you need to keep them interested and involved.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "You are absolutely right. I will take time to practice and to learn to relax and express myself really well. Wish me luck.",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good brother, you will do good",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 3,
        name: "Natalie Portman",
        image: "https://pyxis.nymag.com/v1/imgs/444/e3f/98e53f67d8e1e15e80a2ecaf71a9d1fba0-12-natalie-portman.rsquare.w330.jpg",
        status: "offline",
        chats: [],
    },
    {
        id: 4,
        name: "Brad Pitt",
        image: "https://pyxis.nymag.com/v1/imgs/70a/8bf/035e2a45436f3c1ee8bb609b2beabfd93c-9-brad-pitt.rsquare.w700.jpg",
        status: "away",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "I have to give a presentation on global warming on Friday, and I am so nervous.",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "First of all, you need to understand the subject matter thoroughly. You need to know what is global warming, what causes global warming, and what people should do to abate the effects of global warming",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I have done a lot of research on the subject, and I know I can answer any questions I will receive from the audience.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I should talk about more precisely the sequence of my presentation?",
                self: false,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Yes, what you should present first, second and third",
                self: true,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If that is the case, then I already have an outline. To make it easy for my audience to follow the presentation, I intend to post the outline on the board at all time during my speech.",
                self: false,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "No, I have not thought about that. I better get some statistics from the Internet. I should not have any problems since the Internet has all kinds of data.",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Pictures will keep your audience from being bored. In order for you to succeed, you need to keep them interested and involved.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I went back to school.",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good for you.",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 5,
        name: "Emma Watson",
        image: "https://hips.hearstapps.com/harpersbazaaruk.cdnds.net/15/37/original/original-01emmawatsonsquare-jpg-70e3c897.jpg",
        status: "online",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "I have to give a presentation on global warming on Friday, and I am so nervous.",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "First of all, you need to understand the subject matter thoroughly. You need to know what is global warming, what causes global warming, and what people should do to abate the effects of global warming",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I have done a lot of research on the subject, and I know I can answer any questions I will receive from the audience.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I should talk about more precisely the sequence of my presentation?",
                self: false,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Yes, what you should present first, second and third",
                self: true,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If that is the case, then I already have an outline. To make it easy for my audience to follow the presentation, I intend to post the outline on the board at all time during my speech.",
                self: false,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "No, I have not thought about that. I better get some statistics from the Internet. I should not have any problems since the Internet has all kinds of data.",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Pictures will keep your audience from being bored. In order for you to succeed, you need to keep them interested and involved.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "The less you reveal, the more people can wonder.",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Well said, Emma",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 6,
        name: "Angelina Jolie",
        image: "https://pyxis.nymag.com/v1/imgs/f50/c4b/5307920159c4c030a87da399c2f8b42ab6-18-angelina-jolie-children.rsquare.w700.jpg",
        status: "busy",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "I have to give a presentation on global warming on Friday, and I am so nervous.",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "First of all, you need to understand the subject matter thoroughly. You need to know what is global warming, what causes global warming, and what people should do to abate the effects of global warming",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I have done a lot of research on the subject, and I know I can answer any questions I will receive from the audience.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I should talk about more precisely the sequence of my presentation?",
                self: false,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Yes, what you should present first, second and third",
                self: true,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If that is the case, then I already have an outline. To make it easy for my audience to follow the presentation, I intend to post the outline on the board at all time during my speech.",
                self: false,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "No, I have not thought about that. I better get some statistics from the Internet. I should not have any problems since the Internet has all kinds of data.",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Pictures will keep your audience from being bored. In order for you to succeed, you need to keep them interested and involved.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Talking about love is like dancing about architecture. If I could have any job in the world I'd be a professional Cinderella",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Why don't you start right now?",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 7,
        name: "Robert Downey Jr.",
        image: "https://daman.co.id/daman.co.id/wp-content/uploads/2019/10/Robert-Downey-Jr-Glasses-1.jpg",
        status: "offline",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "I have to give a presentation on global warming on Friday, and I am so nervous.",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "First of all, you need to understand the subject matter thoroughly. You need to know what is global warming, what causes global warming, and what people should do to abate the effects of global warming",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I have done a lot of research on the subject, and I know I can answer any questions I will receive from the audience.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I should talk about more precisely the sequence of my presentation?",
                self: false,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Yes, what you should present first, second and third",
                self: true,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If that is the case, then I already have an outline. To make it easy for my audience to follow the presentation, I intend to post the outline on the board at all time during my speech.",
                self: false,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "No, I have not thought about that. I better get some statistics from the Internet. I should not have any problems since the Internet has all kinds of data.",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Pictures will keep your audience from being bored. In order for you to succeed, you need to keep them interested and involved.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Sometimes i want to punch you in your perfect teeth.",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Everything special about you came out of a bottle",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 8,
        name: "Johnny Depp",
        image: "https://hips.hearstapps.com/harpersbazaaruk.cdnds.net/15/37/original/original-johnny-depp-square-jpg-cc886417.jpg",
        status: "away",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "I have to give a presentation on global warming on Friday, and I am so nervous.",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "First of all, you need to understand the subject matter thoroughly. You need to know what is global warming, what causes global warming, and what people should do to abate the effects of global warming",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I have done a lot of research on the subject, and I know I can answer any questions I will receive from the audience.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I should talk about more precisely the sequence of my presentation?",
                self: false,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Yes, what you should present first, second and third",
                self: true,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If that is the case, then I already have an outline. To make it easy for my audience to follow the presentation, I intend to post the outline on the board at all time during my speech.",
                self: false,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Take off the armour and what are you?",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "We have an army.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I am a huge fan of the way you lose control and turn into an enormous green rage monster!!",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If we can't protect the world you can be damn sure we'll avenge it.",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 9,
        name: "Amber Heard",
        image: "https://pyxis.nymag.com/v1/imgs/d6d/185/b7e24e6db3bbf1a5ffa96cf930df6a43c3-19-amber-heard.rsquare.w700.jpg",
        status: "online",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "I have to give a presentation on global warming on Friday, and I am so nervous.",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "First of all, you need to understand the subject matter thoroughly. You need to know what is global warming, what causes global warming, and what people should do to abate the effects of global warming",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I have done a lot of research on the subject, and I know I can answer any questions I will receive from the audience.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I should talk about more precisely the sequence of my presentation?",
                self: false,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Yes, what you should present first, second and third",
                self: true,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If that is the case, then I already have an outline. To make it easy for my audience to follow the presentation, I intend to post the outline on the board at all time during my speech.",
                self: false,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "No, I have not thought about that. I better get some statistics from the Internet. I should not have any problems since the Internet has all kinds of data.",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Pictures will keep your audience from being bored. In order for you to succeed, you need to keep them interested and involved.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Amber, this might be the last time we ever speak, so please listen to me carefully. Considering you like fighting so much why don’t you go watch",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Even somebody who is sure I’m deserving of all this hate and vitriol, even if you think that I’m lying, you still couldn’t tell me - look me in the eye and tell me - that you think on social media there’s been a fair representation. You cannot tell me that you think that this has been fair.",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 10,
        name: "Keanu Reeves",
        image: "https://pyxis.nymag.com/v1/imgs/654/1f1/08de774c11d89cb3f4ecf600a33e9c8283-24-keanu-reeves.rsquare.w700.jpg",
        status: "busy",
        chats: [],
    },
    {
        id: 11,
        name: "Sandra Bullock",
        image: "https://pyxis.nymag.com/v1/imgs/6f3/ec9/aedc7fd8f2fa424a6d94ac07f5567031f3-10-sandra-bullock.rsquare.w330.jpg",
        status: "offline",
        chats: [
            {
                id: crypto.randomUUID(),
                text: "I have to give a presentation on global warming on Friday, and I am so nervous.",
                self: false,
                timestamp: "2023-04-21T15:40:13.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "First of all, you need to understand the subject matter thoroughly. You need to know what is global warming, what causes global warming, and what people should do to abate the effects of global warming",
                self: true,
                timestamp: "2023-04-21T17:08:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I have done a lot of research on the subject, and I know I can answer any questions I will receive from the audience.",
                self: false,
                timestamp: "2023-04-22T20:10:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I should talk about more precisely the sequence of my presentation?",
                self: false,
                timestamp: "2023-04-22T22:15:10.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Yes, what you should present first, second and third",
                self: true,
                timestamp: "2023-04-28T16:22:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "If that is the case, then I already have an outline. To make it easy for my audience to follow the presentation, I intend to post the outline on the board at all time during my speech.",
                self: false,
                timestamp: "2023-04-28T18:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Good idea! By the way, do you have any facts to back you up? For example, change of climate, yearly disasters",
                self: true,
                timestamp: "2023-04-29T13:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "No, I have not thought about that. I better get some statistics from the Internet. I should not have any problems since the Internet has all kinds of data.",
                self: false,
                timestamp: "2023-04-29T14:00:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Pictures will keep your audience from being bored. In order for you to succeed, you need to keep them interested and involved.",
                self: true,
                timestamp: "2023-04-29T14:30:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "Even somebody who is sure I’m deserving of all this hate and vitriol, even if you think that I’m lying, you still couldn’t tell me - look me in the eye and tell me - that you think on social media there’s been a fair representation. You cannot tell me that you think that this has been fair.",
                self: false,
                timestamp: "2023-04-29T15:27:29.000Z",
            },
            {
                id: crypto.randomUUID(),
                text: "I'm quite an independent person, and I had to be. As a boy and growing into a young man I had to look out for myself. And now I'm very family-oriented. It's a big priority in my life.",
                self: true,
                timestamp: "2023-04-30T12:40:29.000Z",
            },
        ],
    },
    {
        id: 12,
        name: "Hugh Jackman",
        image: "https://pyxis.nymag.com/v1/imgs/359/420/25f52523a6c8c790329ff59e5e164cdece-hugh-jackman.rsquare.w330.jpg",
        status: "away",
        chats: [],
    },
];
